apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: automotive-dev-operator-system
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.build-api: >
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"ado-build-api"}}
